apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: smtp-relay
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: smtp-relay
subjects:
- kind: ServiceAccount
  name: smtp-relay
  namespace: smtp-relay

