apiVersion: v1
kind: Service
metadata:
  name: smtp-relay
spec:
  type: ClusterIP
  ports:
    - port: 25
      targetPort: 8025
      protocol: TCP
      name: smtp
  selector:
    app.kubernetes.io/name: smtp-relay
    app.kubernetes.io/instance: smtp-relay
